<Project>
  <!-- General Settings -->
  <PropertyGroup>
    <LangVersion>Latest</LangVersion>
    <Copyright>Ilya Belyanskiy 2020</Copyright>
    <Authors>Belyanskiy Ilya</Authors>
    <PackageProjectUrl>https://github.com/win7user10/Laraue.EfCoreTriggers</PackageProjectUrl>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Designate all projects as non-package projects by default -->
    <IsPackable>false</IsPackable>
    <PackageOutputPath>$(MSBuildThisFileDirectory)out\packages\</PackageOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>